python cs285/scripts/run_hw1.py \
    --expert_policy_file cs285/policies/experts/Ant.pkl \
    --env_name Ant-v4 \
    --expert_data cs285/expert_data/expert_data_Ant-v4.pkl \
    --exp_name dagger_ant \
    --n_iter 10 \
    --num_agent_train_steps_per_iter 4000 \
    --do_dagger \
    --ep_len 1000 \
    --eval_batch_size 10000 \
    --seed 1234 \
    --n_layers 5 \
    --learning_rate 0.001 \
    --video_log_freq -1