python cs285/scripts/run_hw1.py \
    --expert_policy_file cs285/policies/experts/Ant.pkl \
    --expert_data cs285/expert_data/expert_data_Ant-v4.pkl \
    --env_name Ant-v4 \
    --exp_name bc_ant \
    --n_iter 1 \
    --train_batch_size 500 \
    --num_agent_train_steps_per_iter 8000 \
    --ep_len 1000 \
    --eval_batch_size 10000 \
    --seed 1234 \
    --n_layers 5 \
    --video_log_freq -1